STATUS_QUEUED = "QUEUED"
STATUS_PROCESSING = "PROCESSING"
STATUS_COMPLETED = "COMPLETED"
STATUS_FAILED = "FAILED"

STEP_EMBEDDING = "EMBEDDING"
STEP_DESIGN_PLAN = "DESIGN_PLAN"
STEP_LANDING_PAGE_VARIANT = "LANDING_PAGE_VARIANT"
STEP_PERSIST_RESULT = "PERSIST_RESULT"
STEP_DONE = "DONE"

