services:
  dynamodb-local:
    image: amazon/dynamodb-local:3.3.1
    container_name: landerai-dynamodb-benchmark
    command:
      - -jar
      - DynamoDBLocal.jar
      - -inMemory
      - -sharedDb
    working_dir: /home/dynamodblocal
    ports:
      - "8000:8000"
    cpus: 2.0
    mem_limit: 4g
    restart: "no"
